version: '3'
services:
  kong:
    image: kong:1.2.1-alpine
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database 
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000 
      - 8443:8443 
      - 8001:8001 
      - 8444:8444
    links:
      - kong-database:kong-database
    

  kong-migrations:
    image: kong:1.2.1-alpine
    command: kong migrations bootstrap
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: qweqedq
      KONG_PG_USER: kong
    links:
      - kong-database:kong-database
    restart: on-failure

  kong-database:
    image: postgres:11-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASS: qweqedq
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database/growers.sql:/docker-entrypoint-initdb.d/growers.sql